### ISSUE TITLE
Use casek

### ISSUE THREAD

**Issue by BallagErgely** [sn4k3ch4rm3r/logarlec#21]
# TODO

- [x] A hallgató át akar lépni egyik szobából a másikba

- [x] Szoba frissítése: hallgató és hallgató
- [x] Szoba frissítése: hallgató és oktató
- [x] Szoba frissítése: hallgató maszk nélkül és gáz effekt
- [x] Szoba frissítése: hallgató maszkkal és gáz effekt
- [x] Szoba frissítése: oktató és rongy effekt

- [x] A hallgató felvesz egy tárgyat

- [x] A hallgató használ egy maszkot
- [x] A hallgató használ egy TVSZ-t
- [x] A hallgató használ egy söröspoharat
- [x] A hallgató használ egy tranzisztort
- [x] A hallgató használ egy nedves táblatörlő rongyot

- [x] Két sima szoba összeolvad.
- [ ] Két szoba összeolvad, túl sokan lennének. (Backrooms?)
- [x] Két szoba összeolvad és az egyik mérgező.
- [x] Egy elátkozott szoba ajtajai megjelennek/eltűnnek.
- [x] A hallgató kinyit egy camembert-t
- [x] Egy szoba osztódik
- [x] Hallgató felveszi a logarlécet
- [x] Oktató felveszi a logarlécet
- [x] Hallgató eldob egy tárgyat.
