### ISSUE TITLE
Tesztek implementációja

### ISSUE THREAD

**Issue by sn4k3ch4rm3r** [sn4k3ch4rm3r/logarlec#31]
# TODO

- [ ] A hallgató át akar lépni egyik szobából a másikba

- [ ] Szoba frissítése: hallgató és hallgató
- [ ] Szoba frissítése: hallgató és oktató
- [ ] Szoba frissítése: hallgató maszk nélkül és gáz effekt
- [ ] Szoba frissítése: hallgató maszkkal és gáz effekt
- [ ] Szoba frissítése: hallgató, oktató és rongy effekt

- [ ] A hallgató felvesz egy tárgyat

- [ ] A hallgató használ egy maszkot
- [ ] A hallgató használ egy TVSZ-t
- [ ] A hallgató használ egy söröspoharat
- [ ] A hallgató használ egy tranzisztort
- [ ] A hallgató használ egy nedves táblatörlő rongyot

- [ ] Két sima szoba összeolvad.
- [ ] Két szoba összeolvad, túl sokan lennének. (Ezzel kapcsolatban 2 alternatív lefutást is beadtunk már: backrooms vagy nem történik semmi)
- [ ] Két szoba összeolvad és az egyik mérgező.
- [ ] Egy elátkozott szoba ajtajai megjelennek/eltűnnek.
- [ ] A hallgató kinyit egy camembert-t
- [ ] Egy szoba osztódik
- [ ] Hallgató felveszi a logarlécet
- [ ] Oktató felveszi a logarlécet
- [ ] Hallgató eldob egy tárgyat.
